export const PUBKEY_H_BURNER = Buffer.from([48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48]).toString('hex')
export const PUBKH_LENGTH = 20
export const PUBK_LENGTH = 33
export const UUID_LENGTH = 16
export const TXID_LENGTH = 32

export const LOCK_SCRIPT_LENGTH = 5
export const UNLOCKING_SCRIPT_LENGTH = 2
export const P2PKH_LENGTH = LOCK_SCRIPT_LENGTH + UNLOCKING_SCRIPT_LENGTH
export const MIN_COST_PROPOSAL_SCRIPT_LENGTH = 7
export const MAX_COST_PROPOSAL_SCRIPT_LENGTH = 9
export const APPLICATION_PROPOSAL_SCRIPT_LENGTH = 5
export const CONSTITUTION_PROPOSAL_SCRIPT_LENGTH = 6
export const THREAD_SCRIPT_LENGTH = 5
export const RETHEAD_SCRIPT_LENGTH = 6
export const REWARD_SCRIPT_LENGTH = 4
export const VOTE_SCRIPT_LENGTH = 4